---
title: "Outline for the time.ly backend"
output: html_document
date: "2022-09-18"
---

**Problem**: There are $n$ trains (say GO) trains $T_i$ (for $i \in \{1,\cdots, n\}$) each carrying at most $k$ passengers. At some given time, there are $\ell \gg nk$ passengers boarding the train. To avoid this scenario, we would like passengers to _pre-register_ by inputting a desired arrival _interval_. 

order based off priority: currently wasted time is passengers arriving "on time" for popular buses waiting up to three times as long due to queues. if passengers were willing to arrive later or earlier (since they would be late anyway), we could reassign.

__Solution__: Use greedy algos and ML.

- greedy algo: if we can assign $d$ trains, sort the $\ell_i \gg nk$ corresponding to hour $i$. for the greatest $\ell_i$, assign a train $d$ and compare if $\ell_i > \ell_{i-1}$. If true, then assign another train, if not, assign a train to $\ell_{i-1}$. Repeat until all $d$ trains are assigned. 
- greedy algo: at peak hours, reassign passengers based off of order of registration (first come first serve, FIFO queue), this serves as a weight (depart at is irrelevant). passengers who registered first get reassigned to _optimal hours_.

Where does the ML stuff come in? (aka buzzwords to pitch). Use past data (machine learning) to track peak hours, probably at rush hour. Also use it to track _optimal hours_, AKA hours with the least traffic (influenced by date, event, etc).

## Resources

A list of links:

#### Machine learning

- [Intro to Python](https://www.mygreatlearning.com/blog/python-tutorial-for-beginners-a-complete-guide/#pythonpandas)
- [Statistical modelling in Python](https://www.kite.com/blog/python/statistical-modeling-python-libraries/)
= [Numpy, pandas, and scikit](https://medium.com/personal-project/numpy-pandas-and-scikit-learn-explained-e7336baecedc)
- [Writing first model with StatsModels and scikit_learn](https://stephenjoel2k.medium.com/write-your-first-machine-learning-program-using-statsmodels-and-scikit-learn-bf0c14c9e3d9)
- [Scikit_learn vs StatsModels](https://www.thedataincubator.com/blog/2017/11/08/scikit-learn-vs-statsmodels/)
- [Scikit_learn cheatsheet](https://www.educative.io/blog/scikit-learn-cheat-sheet-classification-regression-methods)
- [Kaggle datasets](https://www.kaggle.com/datasets)
- [Figma](https://www.figma.com/file/o64KuFap0n1647i0UP16QE/Hack-the-North-2022?node-id=723%3A247)

#### Other stuff

-`colab`, `tensorflow`, `pandas`, `pytorch`
